### ISSUE TITLE
I can't start the USB stick

### ISSUE THREAD

**Issue by drakengard780** [jlempen/Surface-Go-2-OpenCore#15]
Good morning, could you give me a hand? I created the stick with OpenCore Unfortunately it doesn't start, it remains stuck on the Windows logo and the open red padlock.

**Comment by jlempen** [comment]
Hi @drakengard780,

If it remains stuck on the Windows logo with the red padlock, it means that your SGO2 is not even able to boot the OpenCore bootloader...
You'll find a whole lot of troubleshooting info about such problems at https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html

But first of all, please be aware that this repo will only work with the "high-end" Intel Core m3-8100Y version of the Surface Go 2.

Then make sure you created your USB stick with one of the methods described in the https://dortania.github.io/OpenCore-Install-Guide/installer-guide/ and that you filled your own PlatformInfo generated with [CorpNewt's GenSMBIOS tool](https://github.com/corpnewt/GenSMBIOS) in the `config.plist` file as described in https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#platforminfo

If the above troubleshooting steps won't fix your problem, you'll need to enable verbose booting in your `config.plist` file in order to see what's going on during your boot process. To do so, set `Misc -> Boot -> PickerMode` to `Builtin` and add `-v` to the `boot-args` line in `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82`. Save your `config.plist` file and reboot. That should show you where the boot process gets stuck and hopefully you'll find a solution to your problem in https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html

**Comment by jlempen** [comment]
One thing that comes to mind is that the folder structure in your EFI partition is wrong. Make sure that the `BOOT` and `OC` folders both reside in an `EFI` folder in your EFI partition!
![image](https://github.com/user-attachments/assets/c70d99a9-f0a5-4b1b-9b96-f1df37121646)

**Comment by jlempen** [comment]
Closed due to no feedback
