### ISSUE TITLE
Tablet periodically locking up in Factorio

### ISSUE THREAD

**Issue by summerboard505** [jlempen/Surface-Go-2-OpenCore#20]
So I've installed Factorio on the Surface Go 2 and it's running fine (fps is stable) but after some time it just locks up. The temperature (PRO TIP: temperature is more accurate from the screen side) is around 60°C. I have followed all the recommendations (disabling prochot, voltageshift) but I think that voltageshift doesn't work. SIP is off.

**Comment by jlempen** [comment]
> but I think that voltageshift doesn't work.

If you check the status of voltageshift with `voltageshift info`, it should give you the current settings and values. If voltageshift doesn't work, it would show zeroes everywhere.

As explained in the readme, BD PROCHOT will activate on the SGO2 at temperatures as low as 60°C ~ 70°C. Once BD PROCHOT kicks in, the CPU will throttle down to 0.4Ghz, making the device more or less unusable. 

That's why BD PROCHOT needs to be disabled in order to increase the performance of the machine.
However, if the CPU continues to be fully loaded with BD PROCHOT disabled, the temperature may increase up to 90°C. Beyond 90°C, the device will become unstable and either crash or power off. 

To avoid this, the temperature needs to be kept under control. There's only a handful of methods to keep the temperature under control (i.e. reduce the temperature as much as possible): enabling macOS's `Low Power Mode` in the battery settings, which basically disables SpeedStep, using voltageshift to undervolt the system and changing the CPU's frequency vectors using Acidanthera's `CPUFriend.kext` with the help of CorpNewt's `CPUFriendFriend`.

All those methods are a tradeoff between processing power and temperature. You can't have processing power without producing heat and you can't have a system running cool with a lot of processing power, at least not with a tiny, passively cooled system such as the SGO2.

So, disabling PB PROCHOT allows us to increase the processing power by avoiding to throttle the CPU, at the cost of reaching very high temperatures. As there's no safety net anymore, the device will crash once it reaches critical temperatures around 90°C.

Hence the only way to avoid the device crashing because of high temperatures is to reduce the heat as much as possible by reducing the game's resolution, fps or level of graphics details.

In essence, you're pushing your tiny and underpowered, passively cooled device to its extreme thermal limits because you're disabling the thermal safety net.

It would be interesting to observe what happens when you play the same game in Windows. I guess the fps would slow down to a crawl at some point in order to keep the temperature in check, the same way it would do in macOS if you didn't disable BD PROCHOT.

**Comment by summerboard505** [comment]
Yeah. I fixed it. Turns out Voltageshift wasn't doing anything.
