### ISSUE TITLE
iMessage broken after updating to Sonoma

### ISSUE THREAD

**Issue by lazd** [jlempen/Surface-Go-2-OpenCore#6]
I had working iMessage, logged in and everything, and after updating to Sonoma with the new Sonoma Airportitlwm, it no longer sends/receives messages... I read something about [itlwm working, but Airportitlem not](https://www.reddit.com/r/hackintosh/comments/186f4ut/comment/kbc1do5/?utm_source=share&utm_medium=web2x&context=3), so it's worth looking into that.

**Comment by lazd** [comment]
I can confirm that itlwm 2.2.0 + HeliPort results in working iMessage again in Sonoma! The menubar widget is pretty bugged out, but it does work.

**Comment by jlempen** [comment]
Well, this repo uses the Alpha version of the Airportitlwm.kext for Sonoma, so issues are to be expected, but the users needs to know about this serious issue. I'll add your findings to the readme, thanks again, @lazd!

**Comment by lazd** [comment]
Totally, we're making hardware do things it wasn't intended to, so bugs are always to be expected! Even with `itlwm.kext` + Heliport, it's still very, uh, interesting. It does automatically connect, but it takes a moment and the menu looks like this at first. If you close/re-open it, it looks normal, but the highlight stays when you move your mouse over it. Fun stuff.

<img width="385" alt="Screenshot 2024-01-21 at 7 28 18 PM" src="https://github.com/jlempen/Surface-Go-2-OpenCore/assets/201344/6277e2ec-5739-435a-92d6-bc8b1c088433">

**Comment by jlempen** [comment]
Interesting stuff, indeed. But at least iMessage works with itlwm.kext and HeliPort.

My take on this issue is that either I downgrade the repo to Ventura or we consider that most people are perfectly happy with working native Wifi and broken iMessage. And for those who need iMessage, they still have the option to disable the AirportItlwm.kext and use itlwm.kext and the HeliPort widget instead, even if the latter has some weird UI artifacts.
In the meantime, let's close this issue and wait for the [OpenIntelWireless](https://github.com/OpenIntelWireless) developers to release a stable v2.3 of the AirportItlwm.kext for Sonoma.
